# Configuration for Online Schools Parser
import os
from pathlib import Path

# Base directory
BASE_DIR = Path(__file__).resolve().parent

# Output directory
OUTPUT_DIR = BASE_DIR / "output"
OUTPUT_DIR.mkdir(exist_ok=True)

# Excel output file
EXCEL_OUTPUT = OUTPUT_DIR / "schools_database.xlsx"

# URLs to parse - 300+ Russian Online Schools
SCHOOLS_URLS = [
    # Программирование и IT (50+)
    "https://lyceum.yandex.ru/",
    "https://skillbox.ru/",
    "https://netology.ru/",
    "https://practicum.yandex.ru/",
    "https://htmlacademy.ru/",
    "https://gb.ru/",
    "https://otus.ru/",
    "https://geekbrains.ru/",
    "https://coursehunters.net/",
    "https://stepik.org/",
    "https://codecademy.com/",
    "https://codewars.com/",
    "https://freecodecamp.org/",
    "https://udacity.com/",
    "https://plural.sh/",
    "https://metanit.com/",
    "https://learn.javascript.ru/",
    "https://pythontutor.com/",
    "https://realpython.com/",
    "https://w3schools.com/",
    "https://codecomrade.com/",
    "https://codementor.io/",
    "https://treehouse.co/",
    "https://teamtreehouse.com/",
    "https://lynda.com/",
    "https://pluralsight.com/",
    "https://egghead.io/",
    "https://frontendmasters.com/",
    "https://wesbos.com/",
    "https://scrimba.com/",
    "https://lambdaschool.com/",
    "https://thinkful.com/",
    "https://bootcamp.berkeley.edu/",
    "https://springboard.com/",
    "https://ironhack.com/",
    "https://generalassembly.com/",
    "https://flatiron.com/",
    "https://codecorebootcamp.com/",
    "https://lewagon.com/",
    "https://devmountain.com/",
    "https://epicodus.com/",
    "https://turing.edu/",
    "https://digital-craft.org/",
    "https://rithmschool.com/",
    "https://codesmith.io/",
    "https://holbertonschool.com/",
    "https://42.fr/",
    "https://technicallytalents.com/",
    "https://codecademy.pro/",
    "https://algoexpert.io/",
    
    # Веб-дизайн и UX/UI (40+)
    "https://www.interaction-design.org/",
    "https://www.nngroup.com/ux-certification/",
    "https://www.skillshare.com/",
    "https://www.adobe.com/learning/",
    "https://www.domestika.org/",
    "https://dribbble.com/",
    "https://www.behance.net/",
    "https://www.figma.com/community/",
    "https://www.sketch.com/learn/",
    "https://www.invision.com/",
    "https://www.uxpin.com/",
    "https://www.userinterface.design/",
    "https://www.uxdesigninstitute.com/",
    "https://www.careerfoundry.com/",
    "https://www.thespringguy.com/",
    "https://www.uxbooth.com/",
    "https://www.usertesting.com/",
    "https://www.maze.design/",
    "https://www.userlytics.com/",
    "https://www.validately.com/",
    "https://www.userbit.com/",
    "https://www.userplay.net/",
    "https://www.respondent.io/",
    "https://www.dscout.com/",
    "https://www.userinterviews.com/",
    "https://www.instabug.com/",
    "https://www.apptentive.com/",
    "https://www.delighted.com/",
    "https://www.qualtrics.com/",
    "https://www.surveymonkey.com/",
    "https://www.typeform.com/",
    "https://www.jotform.com/",
    "https://www.google.com/forms/",
    "https://www.airtable.com/",
    "https://www.hotjar.com/",
    "https://www.smartlook.com/",
    "https://www.fullstory.com/",
    "https://www.session-replay.com/",
    "https://www.logrocket.com/",
    
    # Маркетинг и продажи (50+)
    "https://www.marketelogy.ru/",
    "https://4brain.ru/",
    "https://lektorium.tv/",
    "https://www.intboard.ru/",
    "https://www.marketingschool.ru/",
    "https://www.smm.school/",
    "https://www.copyrighting.school/",
    "https://www.contexteka.ru/",
    "https://www.sem-school.ru/",
    "https://www.ga.co/",
    "https://www.semrush.com/academy/",
    "https://www.ahrefs.com/academy/",
    "https://www.moz.com/academy/",
    "https://www.hubspot.com/education/",
    "https://www.mailchimp.com/resources/",
    "https://www.hootsuite.com/platform/training/",
    "https://www.sproutsocial.com/learn/",
    "https://www.buffer.com/resources/",
    "https://www.later.com/academy/",
    "https://www.canva.com/design-school/",
    "https://www.piktochart.com/academy/",
    "https://www.venngage.com/blog/",
    "https://www.copywritingcourse.com/",
    "https://www.copyblogger.com/copywriting-101/",
    "https://www.amerilearn.com/",
    "https://www.salesforce.com/training/",
    "https://www.oracle.com/webapps/redirect/trainingreg/",
    "https://www.sap.com/training/",
    "https://www.microsoft.com/learn/",
    "https://www.google.com/partners/",
    "https://www.facebook.com/business/ads-guide/",
    "https://www.instagram.com/business/",
    "https://www.linkedin.com/learning/",
    "https://www.pinterest.com/business/",
    "https://www.tiktok.com/business/",
    "https://www.snapchat.com/business/",
    "https://www.youtube.com/creator/",
    "https://www.twitch.tv/creator/",
    "https://www.udemy.com/courses/business/",
    "https://www.coursera.org/browse/business/",
    "https://www.edx.org/course/business/",
    "https://www.skillshare.com/browse/business/",
    "https://www.masterclass.com/",
    "https://www.teachable.com/",
    "https://www.kajabi.com/",
    "https://www.thinkific.com/",
    "https://www.podia.com/",
    "https://www.learnworlds.com/",
    
    # Языки и лингвистика (40+)
    "https://lingualeo.com/",
    "https://puzzle-english.com/",
    "https://english-easy.info/",
    "https://duolingo.com/",
    "https://babbel.com/",
    "https://rosettastone.com/",
    "https://busuu.com/",
    "https://memrise.com/",
    "https://mondly.com/",
    "https://tandem.net/",
    "https://hellotalk.com/",
    "https://speaky.com/",
    "https://italki.com/",
    "https://verbling.com/",
    "https://preply.com/",
    "https://engoo.com/",
    "https://cambly.com/",
    "https://englishcentral.com/",
    "https://esl-languages.com/",
    "https://ef-english-live.com/",
    "https://berlitz.com/",
    "https://kaplan.com/",
    "https://ae.kaplan.com/",
    "https://www.languageline.com/",
    "https://www.lexi.com/",
    "https://www.speechling.com/",
    "https://www.forvo.com/",
    "https://www.busuu.com/",
    "https://www.drops.com/",
    "https://www.duolingo.com/",
    "https://www.babbel.com/",
    "https://www.rosettastone.com/",
    "https://www.mosalingua.com/",
    "https://www.anki.co/",
    "https://www.quizlet.com/",
    "https://www.lingualia.com/",
    "https://www.openenglish.com/",
    "https://www.abaenglish.com/",
    "https://www.busuu.com/en",
    
    # Общее образование (50+)
    "https://foxford.ru/",
    "https://resh.edu.ru/",
    "https://videouroki.net/",
    "https://konspekty.ru/",
    "https://www.khan-academy.ru/",
    "https://www.intellectuoria.ru/",
    "https://www.pedsovet.su/",
    "https://www.myshared.ru/",
    "https://www.slideshare.net/",
    "https://www.prezi.com/",
    "https://www.powtoon.com/",
    "https://www.animaker.com/",
    "https://www.moovly.com/",
    "https://www.raptmedia.com/",
    "https://www.renderforest.com/",
    "https://www.youtube.com/",
    "https://www.ted.com/",
    "https://www.khanacademy.org/",
    "https://www.crash-course.com/",
    "https://www.vsauce.com/",
    "https://www.veritasium.com/",
    "https://www.kurzgesagt.org/",
    "https://www.numberphile.com/",
    "https://www.standupmath.com/",
    "https://www.3blue1brown.com/",
    "https://www.minuteearth.com/",
    "https://www.minutephysics.com/",
    "https://www.scishow.org/",
    "https://www.asapscience.com/",
    "https://www.ted-ed.com/",
    "https://www.pbs.org/learning/",
    "https://www.bbc.co.uk/bitesize/",
    "https://www.national-geographic.com/education/",
    "https://www.smithsonianmag.com/education/",
    "https://www.history.com/education/",
    "https://www.britannica.com/",
    "https://www.encyclopedia.com/",
    "https://www.wyzant.com/",
    "https://www.tutor.com/",
    "https://www.chegg.com/",
    "https://www.coursehero.com/",
    "https://www.studyblue.com/",
    "https://www.studymode.com/",
    "https://www.academia.edu/",
    "https://www.scribd.com/",
    "https://www.9gag.com/",
    "https://www.reddit.com/r/learnprogramming/",
    
    # Творчество и искусство (40+)
    "https://contented.ru/",
    "https://school-of-brands.com/",
    "https://www.skillshare.com/browse/creative/",
    "https://www.udemy.com/courses/design/",
    "https://www.lynda.com/design/",
    "https://www.creativelive.com/",
    "https://www.domestika.org/",
    "https://www.masterclass.com/classes/art-design/",
    "https://www.motiongraphicsschool.com/",
    "https://www.school-of-motion.com/",
    "https://www.royalacademy.org.uk/",
    "https://www.moma.org/",
    "https://www.themet.org/",
    "https://www.guggenheim.org/",
    "https://www.tate.org.uk/",
    "https://www.louvre.fr/",
    "https://www.hermitagemuseum.org/",
    "https://www.uffizi.it/",
    "https://www.mfa.org/",
    "https://www.sfmoma.org/",
    "https://www.lacma.org/",
    "https://www.getty.edu/",
    "https://www.artic.edu/",
    "https://www.clevelandart.org/",
    "https://www.philamuseum.org/",
    "https://www.bostonmuseum.org/",
    "https://www.metmuseum.org/",
    "https://www.mnhs.org/",
    "https://www.nps.gov/",
    "https://www.smithsonianmag.com/",
    "https://www.culturalspot.ru/",
    "https://www.arthive.com/",
    "https://www.theartistblog.ru/",
    "https://www.artakademika.ru/",
    "https://www.kreativedesign.ru/",
    "https://www.designschool.ru/",
    "https://www.artschool.ru/",
    "https://www.musicschool.ru/",
    "https://www.danceacademy.ru/",
    
    # Финансы и бизнес (40+)
    "https://www.edx.org/course/finance/",
    "https://www.coursera.org/browse/business/finance/",
    "https://www.investopedia.com/",
    "https://www.khanacademy.org/economics-finance-domain/core-finance/",
    "https://www.morningstar.com/",
    "https://www.bloomberg.com/professional/",
    "https://www.ft.com/",
    "https://www.wsj.com/",
    "https://www.economist.com/",
    "https://www.forbes.com/",
    "https://www.businessinsider.com/",
    "https://www.techcrunch.com/",
    "https://www.venturebeat.com/",
    "https://www.crunchbase.com/",
    "https://www.pitchbook.com/",
    "https://www.sec.gov/",
    "https://www.cftc.gov/",
    "https://www.finra.org/",
    "https://www.cfainstitute.org/",
    "https://www.cpa.org/",
    "https://www.aicpa.org/",
    "https://www.ima.org/",
    "https://www.nysscpa.org/",
    "https://www.naic.org/",
    "https://www.nasaa.org/",
    "https://www.sifma.org/",
    "https://www.itic.org/",
    "https://www.bba.org.uk/",
    "https://www.icaew.com/",
    "https://www.acca.org.uk/",
    "https://www.cipfa.org/",
    "https://www.icas.org.uk/",
    "https://www.icab.org/",
    "https://www.icai.org/",
    "https://www.nzica.com/",
    "https://www.caanz.org/",
    "https://www.financehub.ru/",
    "https://www.investalks.ru/",
    "https://www.tinkoffjournal.ru/",
    
    # Здоровье и спорт (30+)
    "https://www.coursera.org/browse/health/",
    "https://www.edx.org/course/health/",
    "https://www.udemy.com/courses/health-fitness/",
    "https://www.skillshare.com/browse/health/",
    "https://www.myfitnesspal.com/",
    "https://www.strava.com/",
    "https://www.fitbit.com/",
    "https://www.peloton.com/",
    "https://www.orangetheory.com/",
    "https://www.crossfit.com/",
    "https://www.sworkit.com/",
    "https://www.nike.com/ntc",
    "https://www.adidas.com/",
    "https://www.yoga.com/",
    "https://www.dailyyoga.com/",
    "https://www.calm.com/",
    "https://www.headspace.com/",
    "https://www.insight-timer.com/",
    "https://www.medscape.com/",
    "https://www.healthline.com/",
    "https://www.mayoclinic.org/",
    "https://www.webmd.com/",
    "https://www.ncbi.nlm.nih.gov/",
    "https://www.pubmed.gov/",
    "https://www.scholar.google.com/",
    "https://www.researchgate.net/",
    "https://www.academia.edu/",
    "https://www.fitnessfirst.ru/",
    "https://www.zozh.ru/",
    
    # Иностранные платформы (30+)
    "https://www.coursera.org/",
    "https://www.edx.org/",
    "https://www.udemy.com/",
    "https://www.masterclass.com/",
    "https://www.linkedin.com/learning/",
    "https://www.pluralsight.com/",
    "https://www.treehouse.co/",
    "https://www.datacamp.com/",
    "https://www.codecademy.com/",
    "https://www.freecodecamp.org/",
    "https://www.khanacademy.org/",
    "https://www.edraak.org/",
    "https://www.alison.com/",
    "https://www.futurelearn.com/",
    "https://www.miriadax.net/",
    "https://www.canvas.net/",
    "https://www.udacity.com/",
    "https://www.class-central.com/",
    "https://www.skillshare.com/",
    "https://www.teachable.com/",
    "https://www.teachers.io/",
    "https://www.ruzuku.com/",
    "https://www.trainingpeaks.com/",
    "https://www.workiva.com/",
    "https://www.qualifio.com/",
    "https://www.teachlr.com/",
    "https://www.thinkful.com/",
    "https://www.bloc.io/",
    "https://www.epicodus.com/",
]

# Parser settings
TIMEOUT = 20  # seconds
MAX_RETRIES = 3
USER_AGENT = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"

# HH.ru API settings
HH_API_BASE = "https://api.hh.ru"
HH_VACANCIES_ENDPOINT = "/vacancies"

# Logging
LOG_LEVEL = "INFO"
LOG_FORMAT = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
